---
title: "Tracking Before Tracking?"
subtitle: "Academic performance and expectations in secondary vocational schools in Chile"
author: "Pablo Geraldo (pdgeraldo@g.ucla.edu)"
date: "Nov 15th, 2022"
format: 
  revealjs:
    theme: simple
    width: 1600
    height: 900
    transition: slide
    slide-number: true
editor: visual
---

## About me

I am a (computational) social scientist conducting research across disciplinary boundaries, with a focus on conceptual and methodological *clarification*.

* **Academic background**
  + Currently: PhD Candidate in Sociology and MS in Statistics at UCLA
  + Former: MS in Sociology, work in educational research and public policy (Chile)
  
* **Affiliations**
  + California Center of Population Research (CCPR)
  + Graduate Certificate in Population Studies (Demography)
  
* **Training and collaborations**
  + Sociology, PoliSci, Statistics, Biostats, Economics, Public Policy
  + Collaborators mostly from Statistics and Anthropology

## Horizontal Stratification

## Vocational Sorting

## Achievement and Expectations

## Institutional Context
### TVET in Chile

## Data and Methods
### Sample construction

## Data and Methods
### Identification Strategy

## Results
### Covariate Balance

## Results
### Effects Estimates

## Results
### Difference-in-difference

## Discussions and Conclusions

##
Thank you!

## Results
### Sensitivity Analysis